#!/bin/bash

sudo apt-cache policy eclipse
sudo apt-cache policy eclipse-testng
sudo apt-cache policy eclipse-taf
sudo apt-cache policy eclipse-slf4j-api
sudo apt-cache policy eclipse-pydev
sudo apt-cache policy eclipse-pmd
sudo apt-cache policy eclipse-mylyn
sudo apt-cache policy eclipse-mylyn-git
sudo apt-cache policy eclipse-m2e
sudo apt-cache policy eclipse-jcat
sudo apt-cache policy eclipse-jboss-tools
sudo apt-cache policy eclipse-guava
sudo apt-cache policy eclipse-groovy
sudo apt-cache policy eclipse-lmitor
sudo apt-cache policy firefox-firebug
sudo apt-cache policy firefox-firepath
sudo apt-cache policy firefox-firequery
sudo apt-cache policy firefox-restclient
sudo apt-cache policy firefox-selenium-ide
sudo apt-cache policy idea
sudo apt-cache policy jboss
sudo apt-cache policy jenkins
sudo apt-cache policy maven
sudo apt-cache policy pycharm
sudo apt-cache policy python-tools
sudo apt-cache policy ymersdk-cli
sudo apt-cache policy versant
sudo apt-cache policy postgres
sudo apt-cache policy motd
sudo apt-cache policy cdt2
sudo apt-cache policy enm-ide
sudo apt-cache policy netbeans
sudo apt-cache policy docker-engine
sudo apt-cache policy docker-compose
