#!/bin/sh
### BEGIN INIT INFO
# Provides:          jboss-as
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/Stop JBoss AS DIST v6.1.1
### END INIT INFO
#
#source some script files in order to set and export environmental variables
#as well as add the appropriate executables to $PATH
[ -r /etc/profile.d/java.sh ] && . /etc/profile.d/java.sh
[ -r /etc/profile.d/jboss.sh ] && . /etc/profile.d/jboss.sh


case "$1" in
    start)
        echo "Starting JBoss AS DIST"
        #original:
        #sudo -u jboss sh ${JBOSS_HOME}/bin/standalone.sh

        #updated:
        start-stop-daemon --start --quiet --background --chuid root --exec ${JBOSS_HOME}/bin/standalone.sh
    ;;

    stop)
    echo "Stopping JBoss AS DIST"
        #original:
        #sudo -u jboss sh ${JBOSS_HOME}/bin/jboss-admin.sh --connect command=:shutdown

        #updated:
        start-stop-daemon --start --quiet --background --chuid root --exec ${JBOSS_HOME}/bin/jboss-cli.sh -- --connect command=:shutdown
    ;;

    status)

    ;;

    restart)
    echo "Reloading JBoss AS DIST"
    start-stop-daemon --start --quiet --background --chuid root --exec ${JBOSS_HOME}/bin/jboss-cli.sh -- --connect command=:reload
    ;;
    *)
        echo "Usage: /etc/init.d/jboss-as {start|stop|status|restart}"
        exit 1
    ;;
esac

exit 0
